basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'


# 'basket/' is the prefix (root) for the rest of the urls here:
urlpatterns = [
    path('', views.basket_summary, name='basket_summary'), #the path is the root and then I want to connect this url to a view called 'basket_summary' where we're gonna show all the items in the basket. we can easily access this url through its name 'basket_summary'.
    path('add/', views.basket_add, name='basket_add'), #where we're gonna send the AJAX request created within 'singleproduct.html' off to.
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
# from azbankgateways.urls import az_bank_gateways_urls
# from checkout.bank import go_to_gateway_view, callback_gateway_view

#we use 'namespace' to refer to a view for avoiding hardcoding.
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')), #It's better to separate our URLs into the application level.'' is the root directory and the HomePage. and namespace will allow us later on in the program to kind of access our URLs in a more convenient way.
    path('basket/', include('basket.urls', namespace='basket')), #we can't have two pathes starting from the root.
    path('account/', include('account.urls', namespace='account')),
    path('checkout/', include("checkout.urls", namespace="checkout")), #It creates a connection to our checkout/urls.py file.
    path('orders/', include('orders.urls', namespace='orders')),
    # # bankgetways urls
    # path('bankgateways/', az_bank_gateways_urls()),
    # path('go-to-gateway/', go_to_gateway_view, name='go-to-gateway'),
    # path('callback-gateway/', callback_gateway_view),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#We can either write it like the line below or above.
# if settings.DEBUG:  #while we're working in the development environment (opposite of production environment) we have got "DEBUG = True" and that provides us an additional information when we make mistakes in our project and we can kind of view them in the browser, of course we don't want that to happen in our production environment so we turn that off.
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = 'store' #this name should be equal to the namespace in 'core/urls.py'.

#here we need to connect our URLs to the views.
urlpatterns = [
    path('', views.product_all, name='product_all'), #this is the root directory. this view is gonna be all the products (I could just call this HomePage).
    path('products/<slug:slug>/', views.product_detail, name='product_detail'), #we want to connect the URL 'products/<slug:slug>/' to the individual product page so we've connected this URL to the 'product_detail' view.
    path('categories/<slug:category_slug>/', views.category_list, name='category_list'),
    path('search/', views.product_search, name='product_search'),
]

basket/models.py
from django.db import models

# Create your models here.

store/forms.py
from django import forms #by this we brought in 'forms' module from Django framework.
from store.models import Product, Category #by this we can grap the data from 'Product' table.

# ارث‌بری می‌کنیمforms.Form ارث‌بری کنیم و در کلاس متا هم اسم آن مدلی که قرار است فرم را براساسش بسازیم، می‌نویسیم. در مقابل اما اگر فرم‌مان مستقل است از forms.ModelForm اگه فرمی که می‌خواهیم بسازیم وابسته به مدل خاصی باشد، باید از 
#'forms.ModelForm': Directly tied to a specific model. You specify which model to use in the Meta class, and it automatically generates fields based on that model.
#'forms.Form': Does not have any direct association with a model. You define all fields manually, and it can be used for various purposes (e.g., search forms, login forms).
#let's go ahead and create a new form for our search.
class ProductSearchForm(forms.Form):
    h = forms.CharField()  #we're not gonna build a form, we're gonna utilize Django and tell Django what type of form we want and we do that by basically set  up this variable 'q'('h') (query).Basically we're gonna say from 'forms' we just want to build a character field input. we just told Django that we want to make a new form and we want one input and that's just gonna be a character field. (ساختیم product_search و ویوای به نام views.py رفتیم توی فایل)
    cgry = forms.ModelChoiceField(queryset=Category.objects.exclude(name='default').order_by('name'))#next up we want to add the drop-down facility so not only do we want the user to be able to search for a word, we want to be able to let them select a category we want to search within. 'ModelChoiceField' is gonna create a drop-down choice field.

    #The __init__ method in a Django form is used to customize the form's initialization process. This defines the constructor for the form class. It allows you to pass additional arguments and keyword arguments when creating an instance of the form.
    def __init__(self, *args, **kwargs): #we're gonna return some arguments back
        super().__init__(*args, **kwargs) #This calls the parent class's (forms.Form) constructor, ensuring that any initialization defined in the parent class is also executed. This is essential for maintaining proper functionality.
        self.fields['cgry'].required = False #we're gonna select the field 'cgry' and put it as unrequired

        self.fields['cgry'].label = 'Category' #This sets a custom label for the cgry field that will be displayed in the form.
        self.fields['h'].label = 'Search For' #Similar to the previous line, this sets a custom label for the search input field h, changing its label to "Search For".

        self.fields['h'].widget.attrs.update(
            {'class': 'form-control menudd'})
        self.fields['h'].widget.attrs.update( #This line adds a data attribute called data-toggle, which is commonly used with Bootstrap to enable dropdown functionality when interacting with elements. It indicates that this input field can trigger a dropdown menu.
            {'data-toggle': 'dropdown'})
        #Field Definitions:
            # h: A character field for entering the search term.
            # cgry: A dropdown field for selecting a category, which excludes any category named "default".

basket/views.py
from django.shortcuts import render, get_object_or_404

from django.http import JsonResponse

from store.models import Product

from .basket import Basket

app_name = 'basket' #same as the 'namespace' of the path referred to this directory that I wrote in 'core/urls.py'.

# Create your views here.

def basket_summary(request): # This 'request' is an instance of 'HttpRequest' which contains the details of user request.
    basket = Basket(request) #to be able to grab the user's basket session data (remember we're instantiating the 'Baket' class here. In other word, an instance of the 'Basket' class is created using the incoming 'request'. This initializes the session and retrieves or creates the user's basket.)
    '''
    In your view function 'basket_summary', the line basket = Basket(request) initializes an instance of the 'Basket' class, and this process involves checking the session data for the key 'skey'. Here’s a detailed breakdown of what happens:
    Breakdown of basket = Basket(request)
    Creating an Instance:
    When you call 'Basket(request)', you are invoking the constructor (__init__ method) of the 'Basket' class, passing the current HTTP request object as an argument.
    Session Access:
    Inside the __init__ method of the 'Basket' class, you have:
    python
    self.session = request.session
    basket = self.session.get('skey')

    This retrieves the session data associated with the current request. The self.session.get('skey') line attempts to get the value associated with the key 'skey'. If 'skey' exists in the session, 'basket' will be set to its corresponding value (which is a dictionary). If it does not exist, 'basket' will be set to None.
    Checking for Existence:
    Next, you have:
    python
    if 'skey' not in request.session:
        basket = self.session['skey'] = {}

    This checks if 'skey' is present in the session data. If it is not found, it initializes an empty dictionary and assigns it to self.session['skey']. This means that if a user has not yet added anything to their basket, an empty dictionary will be created and stored under 'skey'.
    Setting the Basket Attribute:
    Finally, you have:
    python
    self.basket = basket

    This line assigns the value of basket (which is either the existing dictionary from the session or a new empty dictionary) to the instance variable self.basket.
    Summary in Your View
    So, when you use:
    python
    def basket_summary(request):
        basket = Basket(request)

    The variable 'basket' will contain an instance of the 'Basket' class.
    The attribute 'self.basket' within that instance will hold either:
        The existing dictionary associated with 'skey', if it exists (representing items in the user's shopping basket).
        An empty dictionary if 'skey' did not exist in session data prior to this point.
    This structure allows you to manage and manipulate basket data easily throughout your application.
    
    '''
    return render(request, 'basket/summary.html', {'basket': basket}) #we're gonna create a new folder is 'templates/store' folder called 'basket' and inside that a page called 'summary.html'.





#some data within a AJAX request (been created in 'singleproduct.html') is gonna be sent off to this view and we need to collect the data that's been sent to this view from our page ('singleproduct.html'):
def basket_add(request): #This defines a function named 'basket_add', which handles adding items to the shopping basket. It takes an HTTP request as an argument.
    #we're gonna need to access to user's basket session data so first of all we grab that.
    basket = Basket(request) #Here, an instance of the 'Basket' class is created using the incoming 'request'. This initializes the session and retrieves or creates the user's basket.
    #if request.method == 'POST':
    #or
    if request.POST.get('action') == 'post':  #This checks if the action specified in the 'POST' request is 'post' which means that if the request l've received from AJAX is a POST request, indicating that this function should process an addition to the basket (we can change the value of 'action' key to whatever we want (other that 'post') in AJAX request and here).
        #When a user submits a form on a webpage, any input fields within that form are sent to the server as part of the POST request.
        #Each input field's name attribute becomes a key in the 'request.POST' dictionary, and its value becomes the corresponding value.
        
        product_id = int(request.POST.get('productid')) #collecting the product id from the AJAX request data #This retrieves the product ID from the AJAX request data and converts it to an integer.
        product_qty = int(request.POST.get('productqty')) #Similarly, this retrieves and converts the product quantity from the 'POST' data.
        #now l've got the actuall product id I can now actually find the product in the database ('Product' model):
        product = get_object_or_404(Product, id=product_id) #we collected that product via its id. Therefor, we have access to all of its information.#This line attempts to retrieve a Product object from the database using its ID. If no product with that ID exists, it raises a 404 error (not found).
        #now we're gonna save that product_id and its qty to the user's session (in actual fact there is a main session for the user and different contexts are gonna be managed and stored under different keys. in our case we stored our data (the product_id and its qty) under a key named 'skey' and put them in a variable called 'basket').
        #'skey' is simply a key that we have chosen to use to access a specific piece of data within the session (in this case, related to the shopping basket).
        basket.add(product=product, qty=product_qty) #This calls a method to add and save the specified product (product_id) and quantity to the basket.
        
        #Building a response to send the data back to the front-end (user) to gonna be available via the front-end:
        #we're now gonna build a response (sending the data back to the user) and what we're gonna return back is the new updated basket quantity:
        basketqty = basket.__len__() #This retrieves the total number of items in the basket by calling ' __len__()' method on the basket.
        # basketqty = sum(item['qty'] for item in basket.basket.values())
        response = JsonResponse({'qty': basketqty}) #A JSON response (dictionary format) is created containing the total quantity of items in the basket.
        return response #Finally, this returns the JSON response back to the client (via AJAX), allowing it to update dynamically without reloading the page.
        #we use JSON because it returns the data in a format that we can then utilize within JavaScript (dictionary format).

# def basket_add(request):
#     if request.method == 'POST':
#         basket = Basket(request)

#         # Get product ID and quantity from POST data
#         product_id = request.POST.get('productid')
#         product_qty = request.POST.get('productqty')

#         if not product_id or not product_qty:
#             return JsonResponse({'error': 'Missing product ID or quantity'}, status=400)

#         try:
#             product_id = int(product_id)
#             product_qty = int(product_qty)
#         except ValueError:
#             return JsonResponse({'error': 'Invalid product ID or quantity'}, status=400)

#         # Retrieve the Product instance
#         product = get_object_or_404(Product, id=product_id)

#         # Add the product to the basket
#         basket.add(product=product, qty=product_qty)

#         # Get the total quantity in the basket
#         basketqty = sum(item['qty'] for item in basket.basket.values())

#         # Return the updated quantity as JSON response
#         return JsonResponse({'qty': basketqty})

#     return JsonResponse({'error': 'Invalid request method'}, status=405)  # Method Not Allowed

'''
The 'Basket' class (within 'basket.py') handles session management for storing items in a user's cart, 
while the 'basket_add' function processes requests to add items to that cart and returns feedback about how many items are currently in it.

in 'Basket' class The instance variables 'self.basket' and 'self.session' are set based on the session data.
This means that every instance of 'Basket' class will have its own session and basket, which are initialized based on the current user's request.
'''

'''
Structure of the basket:

basket = {
'product_id_1': {'price': '10.00', 'qty': 2},
'product_id_2': {'price': '15.50', 'qty': 1},
...
}

example:
basket = {
'1': {'price': '10.00', 'qty': 2},
'2': {'price': '15.50', 'qty': 1}
}
the basket.__len__() method would return the number of unique products currently stored in the basket, not the total quantity of all items. in the above example, there are two unique product IDs in the basket: '1' and '2'.
Therefore, calling basket.__len__() would return 2.
If you wanted to get the total quantity of all items in the basket (which is often what users think of when considering the "length" of a basket), you would need to sum the quantities of each product. Here’s how you could do that:
python
total_quantity = sum(item['qty'] for item in self.basket.values())

In your example:
For Product ID '1', the quantity is 3.
For Product ID '2', the quantity is 1.
So, the total quantity would be:
Total Quantity = 3 (from product ID 1) + 1 (from product ID 2) = 4
'''
# def basket_update(request):
#     basket = Basket(request)
#     if request.POST.get('action') == 'post':
#         product_id = int(request.POST.get('productid'))
#         product_qty = int(request.POST.get('productqty'))
#         basket.update(product=product_id, qty=product_qty)

#         basketqty = basket.__len__()
#         baskettotal = basket.get_total_price()
#         response = JsonResponse({'qty': basketqty, 'subtotal': baskettotal})

templates/store/basket/summary.html
<!--Here is where we're gonna see all the products that we've put in our basket in a nice little list before we can then purchase them.-->
{% extends "../base.html" %}
{% load static %}
{% block title %}Basket Summary{% endblock %}

{% block content %}
<main class="pt-5">
    <div class="container">
      <h1 class="h5">Shopping basket</h1>
      {% for item in basket %} <!--This line automatically calls the '__iter__' method of 'Basket' class.--><!--We're not iterating over the actual basket session data here; we want to iterate over the items that are in the basket—the actual data from the database. Remember, in the session data, we're recording and storing the ID of each product that is in the database. In our session data, we're storing only the ID of each product (not its other attributes).
      What we need to do is take the session data, look at all the IDs of the products we've stored, and extract from the 'Product' database all the product instances corresponding to those IDs. We made a copy of the original basket, and to that copy, we've added a reference by a key named 'product' to the product instance that has an ID equal to what we have stored in our original basket.-->
      <!--an example of that copied 'basket' at final: {'skey': {'8': {'price': 15.99, 'qty': 4, 'product': product8, 'total_price':63.96}, '7': {'price': 12.99, 'qty': 3, 'product': product7, 'total_price':38.97}, '4': {'price': 13.99, 'qty': 1, 'product': product4, 'total_price':13.99}}} where 'product8' is an instance of 'Product' class with id=8.-->
      {% with product=item.product %}<!--Each 'item' in the loop is a dictionary that contains keys like 'price', 'gty', and 'product'.and item itself is a str that is equal to just the key of each item in the basket like '8', '7', and '4'-->
      <!--When you use 'item.product', Django checks if 'item' has an attribute named 'product'. Since item is a dictionary, Django will look for the key 'product' within that dictionary.-->
      <div data-index="{{ product.id }}" class="row mb-4 border rounded shadow-sm product-item">
        <div class="col-md-3 col-lg-2 order-md-first bg-light text-center p-3">
            <div class="photo-container">
                <img class="img-fluid rounded shadow" alt="Product image" src="{{ product.image.url }}">
            </div>
        </div>
        <div class="col-md-9 col-lg-10 ps-md-3 ps-lg-10">
            <a href="{{ product.get_absolute_url }}" class="text-decoration-none text-reset">
                <span style="color: rgb(0, 21, 255);"><h1 class="h5 pt-2">{{ product.title }}</h1></span>
            </a>
            <div class="border rounded mb-3">
                <div class="row p-3 align-items-center"> <!-- Added align-items-center -->
                    <div class="col-6 h6 fw-bold">Subtotal Price: </div>
                    <div class="col-6 text-end fw-bold">£<span id="total-price-{{ product.id }}" class="h6 fw-bold">{{ item.total_price }}</span></div>
                </div>
            </div>
            <div class="row p-3 border rounded">
                <div class="col-12">
                    <label for="select{{ product.id }}">Qty</label>
                    <select id="select{{ product.id }}" class="form-select d-inline-block w-auto">
                        {% for qty in "1234"|make_list %}
                            {% if qty == item.qty|stringformat:"s" %}
                                <option selected>{{ qty }}</option>
                            {% else %}
                                <option value="{{ qty }}">{{ qty }}</option>
                            {% endif %}
                        {% endfor %}
                    </select>
                    <button type="button" id="update-button" data-index="{{ product.id }}"
                            class="btn btn-outline-secondary btn-sm update-button ms-2">
                        Update
                    </button>
                    <button type="button" id="delete-button" data-index="{{ product.id }}"
                            class="btn btn-outline-danger btn-sm delete-button ms-2">
                        Delete
                    </button>
                </div>
            </div>
        </div>
    </div>
    {% endwith %}
    {% endfor %}
    <div class="col-12 text-end mt-4">
        <h4 class="fw-bold">Total Price: £<span id="baskettotal" class="d-inline-flex">{{ basket.get_total_price }}</span></h4>
    </div>
</div>
</main>

<script>
// jQuery to handle the updating of an item in a shopping basket when the "Update" button is clicked.
$(document).on('click', '#update-button', function (e) {////'#add-button' refers to the class, '.add-button' refers to the id. //This line sets up an event listener for click events on any element with the class 'update-button'. The $(document).on() method ensures that even if these buttons are added dynamically after the page has loaded, the event listener will still work.
e.preventDefault(); //In HTML forms, buttons (especially of type "submit") have a default action that typically submits the form data to the server. This can cause the page to reload or navigate to a different URL, depending on how the form is set up.By calling 'e.preventDefault()'', you are telling the browser to stop this default action from occurring. This means that clicking the update button will not cause the page to reload or navigate away.
                    // Instead of allowing the default submission, you can implement custom logic in your JavaScript code. In this case, you want to send an AJAX request to update the item in the shopping basket without refreshing the page.
                    // This allows for a smoother user experience, as users can see updates in real-time without interruptions.
var prodid = $(this).data('index'); //collecting the product ID from the 'Delete' button of that particular item when the button is pressed//This line is executed within the click event handler for the update button. 
    // The $(this) refers to the specific button that was clicked. The data('index') method retrieves the value of the 'data-index' attribute from the clicked button. 
    // This attribute is set in your HTML when rendering the button for each product, and it contains the unique ID of the product associated with that button. T
    // he variable 'prodid' now holds the product ID as a string, which will be used later to identify which item in the basket is being updated.
var selectedQty = $('#select' + prodid + ' option:selected').text(); //The variable 'selectedQty' now holds the value of the selected quantity as a string (e.g., "1", "2", etc.).

// When a user clicks on the "Update" button:
// If 'product.id' is 5, then 'prodid' would be "5".
// The corresponding <select> element would have an ID of select5.
// If a user has selected "2" in that dropdown, then 'selectedQty' would be "2".

//This initiates an AJAX POST request:
$.ajax({
    type: 'POST',
    url: '{% url "basket:basket_update" %}', // The URL where the request is sent to be handled. This ensures that when the AJAX request is made, it points to the correct view handling that action.
    data: { //An object containing data sent to the server:
        productid: prodid, //The ID of the product being updated.
        productqty: selectedQty, //The new quantity selected by the user.
        csrfmiddlewaretoken: "{{ csrf_token }}",
        action: 'post' //A string indicating what action is being performed (in this case, it's just 'post').
    },
    //server responds with data in JSON format, which is passed to this function as the 'json' argument.
    success: function (json) { //This function executes if the AJAX request is successful. The server response is expected to be in JSON format and is passed as an argument (json).
        // Update the displayed quantity in the basket count (if needed)
        document.getElementById("basket-qty").innerHTML = json.qty; //in 'base.html'

        // Update the subtotal price for this specific item
        var newTotalPrice = json.item_total_price; // Assuming you return this from the view
        $('#total-price-' + prodid).text(newTotalPrice);

        // Update the overall baskettotal if needed
        $('#baskettotal').text(json.baskettotal);
    },
    error: function (xhr, errmsg, err) {}
});
});


// jQuery to handle the deleting of an item in a shopping basket when the "Delete" button is clicked.
$(document).on('click', '.delete-button', function (e) { //'#add-button' refers to the class, '.add-button' refers to the id.//This line sets up an event listener for click events on any element with the class 'update-button'. The $(document).on() method ensures that even if these buttons are added dynamically after the page has loaded, the event listener will still work.
e.preventDefault(); //In HTML forms, buttons (especially of type "submit") have a default action that typically submits the form data to the server. This can cause the page to reload or navigate to a different URL, depending on how the form is set up.By calling 'e.preventDefault()'', you are telling the browser to stop this default action from occurring. This means that clicking the update button will not cause the page to reload or navigate away.
                    // Instead of allowing the default submission, you can implement custom logic in your JavaScript code. In this case, you want to send an AJAX request to update the item in the shopping basket without refreshing the page.
                    // This allows for a smoother user experience, as users can see updates in real-time without interruptions.
var prodid = $(this).data('index'); //This line is executed within the click event handler for the delete button. The $(this) refers to the specific button that was clicked. 
// The data('index') method retrieves the value of the 'data-index' attribute from the clicked button. 
// This attribute is set in your HTML when rendering the button for each product, and it contains the unique ID of the product associated with that button. 
// The variable 'prodid' now holds the product ID as a string, which will be used later to identify which item in the basket is being updated.

// When a user clicks on the "Update" button:
// If 'product.id' is 5, then 'prodid' would be "5".
// The corresponding <select> element would have an ID of select5.

//This initiates an AJAX POST request:
$.ajax({
    type: 'POST',
    url: '{% url "basket:basket_delete" %}', // The URL where the request is sent to be handled. This ensures that when the AJAX request is made, it points to the correct view handling that action.
    data: { //An object containing data sent to the server:
        productid: prodid, //The ID of the product being deleted.
        csrfmiddlewaretoken: "{{ csrf_token }}",
        action: 'post' //A string indicating what action is being performed (in this case, it's just 'post').
    },
    //returning that data from the 'basket_update' view and referencing to it via the 'json' word.
    success: function (json) { //This function executes if the AJAX request is successful. The server response is expected to be in JSON format and is passed as an argument (json).
        // Update the displayed quantity in the basket count (if needed)
        $('.product-item[data-index="' + prodid + '"]').remove();
            // Purpose: This line selects the HTML element representing the product item that was just removed from the basket.
            // Selector Explanation:
            // The selector $('.product-item[data-index="' + prodid + '"]') uses jQuery to find a <div> with the class 'product-item' that also has a 'data-index' attribute matching the prodid (line 15, which is the div element that wraps around all of the attachments of an individual product that we added into our basket summary page).
            // This effectively identifies the specific product item in the DOM.
            // Action: The .remove() method removes this element from the DOM, meaning that it will no longer be displayed on the page.
        document.getElementById("baskettotal").innerHTML = json.baskettotal; //It accesses an element with the ID baskettotal and sets its inner HTML to the new baskettotal value returned by the server in json.baskettotal.
        document.getElementById("basket-qty").innerHTML = json.qty        

 
    },
    error: function (xhr, errmsg, err) {}
});
});
</script>
{% endblock %}