account/urls.py
from django.contrib.auth import views as auth_views #the pre-built views for the authentication processes (like Login\Logout processes). we're gonna hook into that and override some of the settings. we can do this in the 'views.py' but we're just gonna lay all this out in the urls.py.
from django.urls import path
from . import views
from django.views.generic import TemplateView
from .forms import (PwdResetConfirmForm, PwdResetForm, UserLoginForm)


app_name = 'account' #it should be the same as 'namespace' in 'path('account/', include('account.urls', namespace='account')),' that we wrote in core/urls.py. It makes it much easier for us to call our urls in our templates for example.

urlpatterns = [
    path('register/', views.account_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>/', views.account_activate, name='activate'), #according to the url in 'account_activation_email.html' we have got the 'uid' (user id) and the 'token'. so there are two things here that we're passing in to our url and we're trying to capture those. 
    # User dashboard
    path('dashboard/', views.dashboard, name='dashboard'), #This new path called 'dashboard' is gonna connect to views.dashboard
    path('login/', auth_views.LoginView.as_view(template_name='account/registration/login.html',
                                                form_class=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/account/login/'), name='logout'), #when a user logs out, the next page, where the user is gonna be taken to, is the login page.
    path('profile/edit/', views.edit_details, name='edit_details'),
    path('profile/delete_user/', views.delete_user, name='delete_user'),
    path('profile/delete_confirm/', TemplateView.as_view(template_name="account/dashboard/delete_confirm.html"), name='delete_confirmation'),
    # Reset password
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="account/password_reset/password_reset_form.html",
                                                                 success_url='password_reset_email_confirm', #to tell the user that "if you can check your email you'll then be able to reset your password".
                                                                 email_template_name='account/password_reset/password_reset_email.html', 
                                                                 form_class=PwdResetForm), name='pwdreset'),

    #'password_reset_confirm/<uidb64>/<token>': This is the format similar to what we’ve done previously when we activated the account so we need to take in these parameters (uidb64) and (token) so that we can verify the user when they click on the link that has been sent to their email.
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset/password_reset_confirm.html',
                                                                                                success_url='/account/password_reset_complete/', 
                                                                                                form_class=PwdResetConfirmForm,), name="password_reset_confirm"),
    #by paying attention to the last two pathes, you will realize that in the first path, we start our 'success_url' with no '/' but in the second path we do. 
    # having a '/' at the start means that we want to continue the url that we're currently using. but when we use '/' it is referring to the root directory. 
    # so in the first path we redirect to 'http://127.0.0.1:8000/account/password_reset/password_reset_email_confirm/' as the success url, but in the second one we redirect to 'http://127.0.0.1:8000/account/password_reset_complete/'as the success url.
    
    path('password_reset/password_reset_email_confirm/',
         TemplateView.as_view(template_name="account/password_reset/reset_status.html"), name='password_reset_done'), #for showing 'Password Reset Success Check your email for instructions'.
    path('password_reset_complete/',
         TemplateView.as_view(template_name="account/password_reset/reset_status.html"), name='password_reset_complete'), #for showing 'Password Reset Completed! login'
    path("addresses/", views.view_address, name="addresses"), #It is like a HomePage for the addresses.
    path("add_address/", views.add_address, name="add_address"), #for this we need a form.
    path("addresses/edit/<slug:id>/", views.edit_address, name="edit_address"), #when we edit we're going to pass in the id of the actuall address we want to edit into the view, so then we can run the query against that id and collect the right address to edit.
    path("addresses/delete/<slug:id>/", views.delete_address, name="delete_address"), #We’re going to do the same type of thing here for deleting the address, so we’re gonna need to be able to identify what we want to delete so the view is going to bring up an address.
    path("addresses/set_default/<slug:id>/", views.set_default, name="set_default"),
    path("user_orders/", views.user_orders, name="user_orders"),
    # Wish List
    path("wishlist", views.wishlist, name="wishlist"),
    path("wishlist/add_to_wishlist/<int:id>", views.add_to_wishlist, name="user_wishlist"), 
    #We need to capture the ID of the product the user clicked on to add it to their wishlist. When the user clicks the button, we'll pass the product ID from the frontend to the 'add_to_wishlist' view.
]

checkout/urls.py
from django.urls import include, path

from . import views

app_name = "checkout" #using 'app_name' makes it easier for us to access the urls from our template.

urlpatterns = [
    path("deliverychoices", views.deliverychoices, name="deliverychoices"),
    path("basket_update_delivery/", views.basket_update_delivery, name="basket_update_delivery"), #This path is gonna pass over the AJAX request (information) to a new view called ‘basket_update_delivery’.
    path("delivery_address/", views.delivery_address, name="delivery_address"),
    path("payment_selection/", views.payment_selection, name="payment_selection"),
    # path('request/', views.send_request, name='request'),
    # path('verify/', views.verify , name='verify'),
    path("payment_complete/", views.payment_complete, name="payment_complete"),
    path("payment_successful/", views.payment_successful, name="payment_successful"),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
# from azbankgateways.urls import az_bank_gateways_urls
# from checkout.bank import go_to_gateway_view, callback_gateway_view

#we use 'namespace' to refer to a view for avoiding hardcoding.
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')), #It's better to separate our URLs into the application level.'' is the root directory and the HomePage. and namespace will allow us later on in the program to kind of access our URLs in a more convenient way.
    path('basket/', include('basket.urls', namespace='basket')), #we can't have two pathes starting from the root.
    path('account/', include('account.urls', namespace='account')),
    path('checkout/', include("checkout.urls", namespace="checkout")), #It creates a connection to our checkout/urls.py file.
    path('orders/', include('orders.urls', namespace='orders')),
    # # bankgetways urls
    # path('bankgateways/', az_bank_gateways_urls()),
    # path('go-to-gateway/', go_to_gateway_view, name='go-to-gateway'),
    # path('callback-gateway/', callback_gateway_view),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#We can either write it like the line below or above.
# if settings.DEBUG:  #while we're working in the development environment (opposite of production environment) we have got "DEBUG = True" and that provides us an additional information when we make mistakes in our project and we can kind of view them in the browser, of course we don't want that to happen in our production environment so we turn that off.
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = 'store' #this name should be equal to the namespace in 'core/urls.py'.

#here we need to connect our URLs to the views.
urlpatterns = [
    path('', views.product_all, name='product_all'), #this is the root directory. this view is gonna be all the products (I could just call this HomePage).
    path('products/<slug:slug>/', views.product_detail, name='product_detail'), #we want to connect the URL 'products/<slug:slug>/' to the individual product page so we've connected this URL to the 'product_detail' view.
    path('categories/<slug:category_slug>/', views.category_list, name='category_list'),
    path('search/', views.product_search, name='product_search'),
]

checkout/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _ #translation tools for implementing translation throughout the whole application.

# Create your models here.
#We’re gonna create the table below to save the different types of delivery options I’m going to offer in my system. 
# So we want to store for example delivery choices as a list of options here. There might be three main (different types of) delivery choices that the user can choose from.
class DeliveryOptions(models.Model):
    """
    The Delivery methods table contining all delivery
    """

    DELIVERY_CHOICES = [  #This is a class-level constant that defines the available delivery methods as a list of tuples of (value, display name). 
        ("IS", "In Store"),
        ("HD", "Home Delivery"),
        ("DD", "Digital Delivery"),
    ]

    delivery_name = models.CharField(
        verbose_name=_("delivery_name"),
        help_text=_("Required"),
        max_length=255,
    )
    delivery_price = models.DecimalField(
        verbose_name=_("delivery price"),
        help_text=_("Maximum 999.99"),
        error_messages={
            "name": {
                "max_length": _("The price must be between 0 and 999.99."),
            },
        },
        max_digits=5,
        decimal_places=2,
    )
    delivery_method = models.CharField(
        choices=DELIVERY_CHOICES, #The option that the user selected from the available options in the 'DELIVERY_CHOICES' list above.
        verbose_name=_("delivery_method"),
        help_text=_("Required"),
        max_length=255,
    )
    delivery_timeframe = models.CharField( #we're gonna set a manual time frame (one to two days).
        verbose_name=_("delivery timeframe"),
        help_text=_("Required"),
        max_length=255,
    )
    delivery_window = models.CharField( #This is just gonna refer to the time of day that your package might be delivered
        verbose_name=_("delivery window"),
        help_text=_("Required"),
        max_length=255,
    )
    order = models.IntegerField(verbose_name=_("list order"), help_text=_("Required"), default=0) #An 'IntegerField' that determines the order in which delivery options appear in lists or dropdowns. It defaults to 0.
    is_active = models.BooleanField(default=True) #we can make the delivery option active or inactive, based upon whether we want to provide that service.

    class Meta:
        verbose_name = _("Delivery Option")
        verbose_name_plural = _("Delivery Options")

    def __str__(self):
        return self.delivery_name


# class PaymentSelections(models.Model):#This model stores different types of payment selections available for customers during checkout. we can hook this up to the payment page And I can then output the different payment selections that are available and I can then make them active or inactive.
#     """
#     Store payment options
#     """

#     name = models.CharField(
#         verbose_name=_("name"),
#         help_text=_("Required"),
#         max_length=255,
#     )

#     is_active = models.BooleanField(default=True)

#     class Meta:
#         verbose_name = _("Payment Selection")
#         verbose_name_plural = _("Payment Selections")

#     def __str__(self):
#         return self.name

templates/checkout/delivery_address.html
{% extends "../store/base.html" %}
{% load static %}
{% block title %}Delivery Addresses{%endblock %}
{% block content %}

<main class="pt-5">
    <div class="container">
      <div class="col-12">
    <h1 class="h2">Delivery Address</h1>
  </div>
  <div class="col-12">
    <p>Please select your delivery address</p>
  </div>
  <hr />
</div>


<div class="container">
  <div class="row g-3">
    {% if addresses|length == 0 %}
    <div class="col-12">There are no delivery addresses, <a href="{% url 'account:add_address' %}">add address</a></div>
    {% else %}
    <div class="col-md-4 col-lg-4 order-md-last p-0 order-3">
    
        <div class="d-flex bd-highlight ms-0">
            <div class="p-2 flex-grow-1 bd-highlight">Sub Total:</div>

            <div class="p-2 bd-highlight"><span class="fw-bold h5">£</span><span id="sub_total"
                class="fw-bold h5">{{basket.get_total_price}}</span></div>
          </div>
          <div class="d-flex bd-highlight">
            <div class="p-2 flex-grow-1 bd-highlight">Delivery Cost:</div>
            <div class="p-2 bd-highlight"><span class="fw-bold h5">£</span><span id="delivery_price"
                class="fw-bold h5">{{basket.get_delivery_price}}</span></div>
          </div>
          <div class="d-flex bd-highlight">
            <div class="p-2 flex-grow-1 bd-highlight">Total:</div>
            <div class="p-2 bd-highlight"><span class="fw-bold h5">£</span><span id="total"
                class="fw-bold h5">{{basket.get_ttotal_price}}</span></div>
          </div>
<a role="button" href="{% url 'checkout:payment_selection' %}" class="btn btn-success fw-bold w-100" type="button">Pay Securely</a>
</div>
    
    <div class="col-md-7 col-lg-8">
      {% for address in addresses %}
      {% if not address.default %}
        <h1 class="h5 pt-4">Other Addresses</h1>
      {% endif %}
      <div class="card mb-3 border-1 rounded-0 product-item me-md-4" data-index="{{option.id}}">
        <div class="row g-0">
          <div class="col">
            <div class="card pb-3 rounded-0">
              <div class="card-header bg-white small text-muted">
                {% if address.default %}
                Selected
                {% endif %}
                &nbsp;
              </div>
              <div class="card-body small pb-1">
                <p class="card-text m-0 fw-bold">{{address.full_name}}</p>
                <p class="card-text m-0">{{address.address_line}}</p>
                <p class="card-text m-0">{{address.address_line2}}</p>
                <p class="card-text m-0">{{address.town_city}}</p>
                <p class="card-text m-0">{{address.postcode}}</p>
                <p class="card-text m-0">Phone number: {{address.phone}}</p>
                <div class="pt-5">
                  <a href="{% url 'account:edit_address' address.id %}" class="text-decoration-none">Edit</a>
                  {% if not address.default %}
                  | <a href="{% url 'account:set_default' address.id %}" class="text-decoration-none">Select</a>
                  {% endif %}
                </div>
              </div>
            </div>
            </a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    {% endif %}
  </div>

</div>
</main>
{% endblock %}

templates/checkout/delivery_choices.html
<!-- copied from the summary.html -->
{% extends "../store/base.html" %}
{% load static %}
{% block title %}Delivery Options{%endblock %}
{% block content %}
<main class="pt-5">
<div class="container">
  <div class="col-12">
    <h1 class="h2">Delivery Options</h1>
  </div>
  <div class="col-12">
    <p>Select your preferred delivery option:</p>
  </div>
  <hr />
</div>
<!-- outputing the delivery options: -->
<div class="container">
    <!--output any messages on our page-->
    {% if messages %}
    <div class="alert alert-warning" alert-{{ message.tags }} role="alert">
      {% for message in messages  %}
        {{message|safe}}
      {% endfor %}
    </div>
    {% endif %}
      <div class="row g-3">
        {% if deliveryoptions|length == 0 %}<!--If there are no delivery options (i.e., 'deliveryoptions' has a length of 0), the code inside this conditional block will be executed:-->
        <div class="col-12">There are no delivery options <a href="{% url 'store:product_all' %}">Shop</a></div>
        {% else %}
        <div class="col-md-4 col-lg-4 order-md-last p-0 order-3"> <!--a section to put the items on the right hand side. -->
          <div class="d-flex bd-highlight ms-0">
            <div class="p-2 flex-grow-1 bd-highlight">Sub Total:</div>

            <div class="p-2 bd-highlight"><span class="fw-bold h5">£</span><span id="sub_total"
                class="fw-bold h5">{{basket.get_total_price}}</span></div>
          </div>
          <div class="d-flex bd-highlight">
            <div class="p-2 flex-grow-1 bd-highlight">Delivery Cost:</div>
            <div class="p-2 bd-highlight"><span class="fw-bold h5">£</span><span id="delivery_price"
                class="fw-bold h5">{{basket.get_delivery_price}}</span></div>
          </div>
          <div class="d-flex bd-highlight">
            <div class="p-2 flex-grow-1 bd-highlight">Total:</div>
            <div class="p-2 bd-highlight"><span class="fw-bold h5">£</span><span id="total"
                class="fw-bold h5">{{basket.get_ttotal_price}}</span></div>
          </div>
          
          <a role="button" href="{% url "checkout:delivery_address" %}" class="btn btn-success fw-bold w-100"
            type="button">Pay Securely</a>
        </div>
        <div class="col-md-7 col-lg-8"> <!--a section for the left hand side-->
          
          <!--We’re no going to grab the options inside the deliveryoptions (That’s the data that we sent across from the ‘deliveryoptions’ view.) here we just create a new card for each item-->
          {% for option in deliveryoptions %}
          <div class="card mb-3 border-1 rounded-0 product-item me-md-4" data-index="{{option.id}}">
            <div class="row g-0">
              <div class="col-md-2 ps-3 ps-md-4">
                <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-truck mt-2"
                  viewBox="0 0 16 16">
                  <path
                    d="M0 3.5A1.5 1.5 0 0 1 1.5 2h9A1.5 1.5 0 0 1 12 3.5V5h1.02a1.5 1.5 0 0 1 1.17.563l1.481 1.85a1.5 1.5 0 0 1 .329.938V10.5a1.5 1.5 0 0 1-1.5 1.5H14a2 2 0 1 1-4 0H5a2 2 0 1 1-3.998-.085A1.5 1.5 0 0 1 0 10.5v-7zm1.294 7.456A1.999 1.999 0 0 1 4.732 11h5.536a2.01 2.01 0 0 1 .732-.732V3.5a.5.5 0 0 0-.5-.5h-9a.5.5 0 0 0-.5.5v7a.5.5 0 0 0 .294.456zM12 10a2 2 0 0 1 1.732 1h.768a.5.5 0 0 0 .5-.5V8.35a.5.5 0 0 0-.11-.312l-1.48-1.85A.5.5 0 0 0 13.02 6H12v4zm-9 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm9 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z" />
                </svg>
              </div>
              <div class="col-md-9 ps-md-1">
                <div class="card-body p-1">
                  <p class="card-text ps-2 mb-1 pt-1 fw-bold">{{option.delivery_name}}</p>
                  <p class="card-text ps-2 pb-3">Your order should be delivered within {{option.delivery_timeframe}}.</p>
                </div>
              </div>
              <!--radio button: We have got an option for the user to actually select so that we can then determine the Delivery Cost and the Total. And we will hook that up with AJAX so that we can get a value every time the user clicks on one of the delivery options.-->
              <div class="col-md-1 ps-md-1">
                <input class="align-middle h-100" type="radio" name="deliveryOption" id="{{option.id}}"
                  value="{{option.id}}">
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
        {% endif %}
      </div>
    </div>
    
    <script>
        //We’re looking for (trying to capture and detect a change on any of those radio buttons that we’ve created) the type radio (that’s what we have just set up in the picture above and the name deliveryOptions ). We’re using jQuery here:
    //   $('input[type=radio][name=deliveryOption]').on('change', function(e) {
    //     e.preventDefault();
    $(document).ready(function() {
        //To ensure that the selected radio button remains marked after a page refresh, we can utilize client-side storage options like Local Storage or Session Storage. These methods allow you to save the state of the radio button selection and restore it when the page loads again.
        //Local Storage:it allows you to store data with no expiration time, meaning it will persist even after the browser is closed and reopened. Here’s how to implement this:
        //Using Session Storage: If you prefer to use Session Storage, which clears when the browser tab is closed, you can follow similar steps:
    
    //I'm using Local Storage:

    // Check if there's a saved selection in Local Storage:
    const savedSelection = localStorage.getItem('selectedDeliveryOption'); //This line retrieves a value from the browser's Local Storage using the key 'selectedDeliveryOption'. If a user has previously selected a delivery option, this value will be stored.
    if (savedSelection) {
        // Set the radio button to checked based on saved selection
        $('input[name="deliveryOption"][value="' + savedSelection + '"]').prop('checked', true); //If savedSelection is not null (meaning an option was previously selected), this line finds the radio button with the corresponding value and sets its checked property to true. This visually marks the radio button as selected when the page is refreshed.
    }

    // Event listener for radio button changes:
    $('input[type=radio][name=deliveryOption]').on('change', function() {
        // Save the selected value to Local Storage
        localStorage.setItem('selectedDeliveryOption', $(this).val());
        
        // Optionally, perform your AJAX call here
        $.ajax({
          type: "POST", //AJAX requires a delivery method type which is gonna be 'POST' in this case. 
          url: '{% url "checkout:basket_update_delivery" %}', //we're gonna send this information which is within 'data' (AJAX request), there.
          //what we're gonna send across:
          data: {
            deliveryoption: $(this).val(), //We have selected a radio button, so the ‘$(‘input[type=radio][….’ line is referring to the radio button that user has selected,so the value that we’re collecting is the actual option.id (value=“{{ option.id }}”). So this is going to get the idea of the delivery option that user selected.
            csrfmiddlewaretoken: "{{csrf_token}}",
            action: "post",
          },
          //Now we’ve done the above lines we should be able to send data (AJAX request) to the ‘basket_update_delivery’ view within checkout app.

          //returning from the 'basket_update_delivery' view:
          success: function (json) {
            document.getElementById("total").innerHTML = json.total;
            document.getElementById("delivery_price").innerHTML = json.delivery_price;
          },
          //So now we’ve made the changes based upon successfully sending information to the backend and it’s been returned, we have updated the elements on our page.
          error: function (xhr, errmsg, err) {},
        });
        
      });
    });
    </script>
</main>
{% endblock %}

templates/checkout/payment_selection.html
{% extends "../store/base.html" %}
{% load static %}
{% block title %}Payment Selection{%endblock %}
{% block content %}

<main class="pt-5">
  <div class="container">
    <div class="col-12">
      <h1 class="h2">Payment Selection</h1>
    </div>
    <div class="col-12">
      <p>Please select your payment option</p>
    </div>
    <hr />
  </div>

  <div class="container">
    <div class="row g-3">
      <div class="col-md-4 col-lg-4 order-md-last p-0 order-3">
        <div class="d-flex bd-highlight ms-0">
          <div class="p-2 flex-grow-1 bd-highlight">Sub Total:</div>
          <div class="p-2 bd-highlight"><span class="fw-bold h5">£</span><span id="sub_total"
              class="fw-bold h5">{{basket.get_total_price}}</span></div>
        </div>
        <div class="d-flex bd-highlight">
          <div class="p-2 flex-grow-1 bd-highlight">Delivery Cost:</div>
          <div class="p-2 bd-highlight"><span class="fw-bold h5">£</span><span id="delivery_price"
              class="fw-bold h5">{{basket.get_delivery_price}}</span></div>
        </div>
        <div class="d-flex bd-highlight">
          <div class="p-2 flex-grow-1 bd-highlight">Total:</div>
          <div class="p-2 bd-highlight"><span class="fw-bold h5">£</span><span id="total"
              class="fw-bold h5">{{basket.get_ttotal_price}}</span></div>
        </div>
      </div>
      <div class="col-md-7 col-lg-8 pe-0 pe-md-5">
        <a href="#" id="paypal-button" class="paypal-button col-md-7 col-lg-12 pe-0 pe-md-4" role="button"
          onclick="handlePayPalClick(event)">
          PayPal
        </a>
      </div>
    </div>
  </div>
</main>
<style>
  .paypal-button {
    display: inline-block;
    padding: 15px 20px;
    /* Adjust padding for size */
    font-size: 20px;
    /* Font size to make it larger */
    color: white;
    /* Text color */
    background-color: #ffc439;
    /* PayPal yellow color */
    border: none;
    /* No border */
    border-radius: 5px;
    /* Slightly rounded corners */
    text-align: center;
    /* Center the text */
    text-decoration: none;
    /* Remove underline from link */
    font-family: 'Helvetica Neue', Arial, sans-serif;
    /* Use a similar font to PayPal */
    font-weight: bold;
    /* Make the text bold */
    cursor: pointer;
    /* Pointer cursor on hover */
    transition: background-color 0.3s;
    /* Smooth transition for hover effect */
  }

  .paypal-button:hover {
    background-color: #e6b82f;
    /* Darker yellow on hover */
  }
</style>
<script>
  //we're gonna create an AJAX request, we're gonna send the information about the current order of the user that currently is stored in their session data to the server ('payment_complete' view) and create a new order instance from it for 'Order' table.
  function handlePayPalClick(event) {
    event.preventDefault(); // Prevent the default anchor click behavior

    // Make an AJAX request to save the purchase
    $.ajax({
      url: "{% url 'checkout:payment_complete' %}", // URL for creating a new instance of the 'Order' class.
      type: "POST", // Use POST method
      data: {
        // You can send additional data if needed, like CSRF token
        csrfmiddlewaretoken: '{{ csrf_token }}' // Include CSRF token for security
      },
      success: function (response) {
        // Redirect to the success page if the order instance is created ans saved successfully in 'Order' table.
        window.location.href = "{% url 'checkout:payment_successful' %}"; // Redirect to success page
      },
      error: function (xhr, status, error) {
        console.error("Error saving purchase:", error);
        alert("There was an error processing your payment. Please try again.");
      }
    });
  }
</script>
{% endblock %}

templates/checkout/payment_successful.html
{% extends "../store/base.html" %}
{% load static %}
{% block title %}Payment Successful{%endblock %}
{% block content %}

<main class="pt-5">
    <div class="container">
      <div class="col-12">
    <h1 class="h2">Payment Successful!</h1>
  </div>
  <hr />
  <div class="col-12">
    <p>View all <a href="{% url 'account:user_orders'%}">orders</a></p>
  </div>
  <div class="col-12">
    <h3>Order Summary:</h3>
  </div>
</div>
<hr />
 <div class="container">
    {% if latest_order %}
    <div class="row g-3 mb-4">
        <div class="col-12 bg-light p-4 rounded shadow-sm d-flex justify-content-between">
            <div class="d-flex align-items-center">
                <div class="pe-3 text-muted small">{{ latest_order.created|date:"F j, Y, g:i a" }}</div>
                <div class="dropdown">
                    <a class="text-reset text-decoration-none dropdown-toggle post-title" href="#" role="link" id="dropdownLink" data-bs-toggle="dropdown" aria-expanded="false">
                        Dispatched to
                        <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" class="bi bi-chevron-down" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/>
                        </svg>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="dropdownLink">
                        <li class="dropdown-item small">{{ latest_order.full_name }}</li>
                        <li class="dropdown-item small">{{ latest_order.address1 }}</li>
                        <li class="dropdown-item small">{{ latest_order.address2 }}</li>
                        <li class="dropdown-item small">{{ latest_order.postcode }}</li> <!-- Adjusted to match your field name -->
                    </ul>
                </div>
            </div>
            <div class="text-end fw-bold">
                Total paid: <span class="text-success">£{{ latest_order.total_paid }}</span>
            </div>
        </div>
    
        <div class="col-md-5 col-lg-4 order-md-last p-0 mt-2">
            <div class="d-grid gap-2">
                <button class="btn btn-success" type="button">Problem with order</button>
                <button class="btn btn-warning" type="button">Leave a review</button>
            </div>
        </div>
    
        <div class="col-md-7 col-lg-8 p-0 mt-2">
            {% for item in latest_order.items.all %}
            <div class="card mb-3 border-0 shadow-sm">
                <div class="row g-0">
                    <div class="col-md-2 d-none d-md-block">
                        <img class="img-fluid rounded-start" alt="{{ item.product.name }}" src="{{ item.product.image.url }}">
                    </div>
                    <div class="col-md-10">
                        <div class="card-body p-3">
                            <a class="text-decoration-none text-dark" href="{{ item.product.get_absolute_url }}">
                                <p class="card-text small">{{ item.product|title }}</p>
                            </a>
                            <p class="small text-muted">Quantity: {{ item.quantity }}</p> <!-- Display quantity -->
                            <p class="small text-muted">Price: £{{ item.price }}</p> <!-- Display price -->
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    {% endif %}
  </div>
</main>
{% endblock %}