account/urls.py
from django.contrib.auth import views as auth_views #the pre-built views for the authentication processes (like Login\Logout processes). we're gonna hook into that and override some of the settings. we can do this in the 'views.py' but we're just gonna lay all this out in the urls.py.
from django.urls import path
from . import views
from django.views.generic import TemplateView
from .forms import (PwdResetConfirmForm, PwdResetForm, UserLoginForm)


app_name = 'account' #it should be the same as 'namespace' in 'path('account/', include('account.urls', namespace='account')),' that we wrote in core/urls.py. It makes it much easier for us to call our urls in our templates for example.

urlpatterns = [
    path('register/', views.account_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>/', views.account_activate, name='activate'), #according to the url in 'account_activation_email.html' we have got the 'uid' (user id) and the 'token'. so there are two things here that we're passing in to our url and we're trying to capture those. 
    # User dashboard
    path('dashboard/', views.dashboard, name='dashboard'), #This new path called 'dashboard' is gonna connect to views.dashboard
    path('login/', auth_views.LoginView.as_view(template_name='account/registration/login.html',
                                                form_class=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/account/login/'), name='logout'), #when a user logs out, the next page, where the user is gonna be taken to, is the login page.
    path('profile/edit/', views.edit_details, name='edit_details'),
    path('profile/delete_user/', views.delete_user, name='delete_user'),
    path('profile/delete_confirm/', TemplateView.as_view(template_name="account/dashboard/delete_confirm.html"), name='delete_confirmation'),
    # Reset password
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="account/password_reset/password_reset_form.html",
                                                                 success_url='password_reset_email_confirm', #to tell the user that "if you can check your email you'll then be able to reset your password".
                                                                 email_template_name='account/password_reset/password_reset_email.html', 
                                                                 form_class=PwdResetForm), name='pwdreset'),

    #'password_reset_confirm/<uidb64>/<token>': This is the format similar to what we’ve done previously when we activated the account so we need to take in these parameters (uidb64) and (token) so that we can verify the user when they click on the link that has been sent to their email.
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset/password_reset_confirm.html',
                                                                                                success_url='/account/password_reset_complete/', 
                                                                                                form_class=PwdResetConfirmForm,), name="password_reset_confirm"),
    #by paying attention to the last two pathes, you will realize that in the first path, we start our 'success_url' with no '/' but in the second path we do. 
    # having a '/' at the start means that we want to continue the url that we're currently using. but when we use '/' it is referring to the root directory. 
    # so in the first path we redirect to 'http://127.0.0.1:8000/account/password_reset/password_reset_email_confirm/' as the success url, but in the second one we redirect to 'http://127.0.0.1:8000/account/password_reset_complete/'as the success url.
    
    path('password_reset/password_reset_email_confirm/',
         TemplateView.as_view(template_name="account/password_reset/reset_status.html"), name='password_reset_done'), #for showing 'Password Reset Success Check your email for instructions'.
    path('password_reset_complete/',
         TemplateView.as_view(template_name="account/password_reset/reset_status.html"), name='password_reset_complete'), #for showing 'Password Reset Completed! login'
    path("addresses/", views.view_address, name="addresses"), #It is like a HomePage for the addresses.
    path("add_address/", views.add_address, name="add_address"), #for this we need a form.
    path("addresses/edit/<slug:id>/", views.edit_address, name="edit_address"), #when we edit we're going to pass in the id of the actuall address we want to edit into the view, so then we can run the query against that id and collect the right address to edit.
    path("addresses/delete/<slug:id>/", views.delete_address, name="delete_address"), #We’re going to do the same type of thing here for deleting the address, so we’re gonna need to be able to identify what we want to delete so the view is going to bring up an address.
    path("addresses/set_default/<slug:id>/", views.set_default, name="set_default"),
    path("user_orders/", views.user_orders, name="user_orders"),
    # Wish List
    path("wishlist", views.wishlist, name="wishlist"),
    path("wishlist/add_to_wishlist/<int:id>", views.add_to_wishlist, name="user_wishlist"), 
    #We need to capture the ID of the product the user clicked on to add it to their wishlist. When the user clicks the button, we'll pass the product ID from the frontend to the 'add_to_wishlist' view.
]

basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'


# 'basket/' is the prefix (root) for the rest of the urls here:
urlpatterns = [
    path('', views.basket_summary, name='basket_summary'), #the path is the root and then I want to connect this url to a view called 'basket_summary' where we're gonna show all the items in the basket. we can easily access this url through its name 'basket_summary'.
    path('add/', views.basket_add, name='basket_add'), #where we're gonna send the AJAX request created within 'singleproduct.html' off to.
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
# from azbankgateways.urls import az_bank_gateways_urls
# from checkout.bank import go_to_gateway_view, callback_gateway_view

#we use 'namespace' to refer to a view for avoiding hardcoding.
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')), #It's better to separate our URLs into the application level.'' is the root directory and the HomePage. and namespace will allow us later on in the program to kind of access our URLs in a more convenient way.
    path('basket/', include('basket.urls', namespace='basket')), #we can't have two pathes starting from the root.
    path('account/', include('account.urls', namespace='account')),
    path('checkout/', include("checkout.urls", namespace="checkout")), #It creates a connection to our checkout/urls.py file.
    path('orders/', include('orders.urls', namespace='orders')),
    # # bankgetways urls
    # path('bankgateways/', az_bank_gateways_urls()),
    # path('go-to-gateway/', go_to_gateway_view, name='go-to-gateway'),
    # path('callback-gateway/', callback_gateway_view),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#We can either write it like the line below or above.
# if settings.DEBUG:  #while we're working in the development environment (opposite of production environment) we have got "DEBUG = True" and that provides us an additional information when we make mistakes in our project and we can kind of view them in the browser, of course we don't want that to happen in our production environment so we turn that off.
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = 'store' #this name should be equal to the namespace in 'core/urls.py'.

#here we need to connect our URLs to the views.
urlpatterns = [
    path('', views.product_all, name='product_all'), #this is the root directory. this view is gonna be all the products (I could just call this HomePage).
    path('products/<slug:slug>/', views.product_detail, name='product_detail'), #we want to connect the URL 'products/<slug:slug>/' to the individual product page so we've connected this URL to the 'product_detail' view.
    path('categories/<slug:category_slug>/', views.category_list, name='category_list'),
    path('search/', views.product_search, name='product_search'),
]

store/forms.py
from django import forms #by this we brought in 'forms' module from Django framework.
from store.models import Product, Category #by this we can grap the data from 'Product' table.

# ارث‌بری می‌کنیمforms.Form ارث‌بری کنیم و در کلاس متا هم اسم آن مدلی که قرار است فرم را براساسش بسازیم، می‌نویسیم. در مقابل اما اگر فرم‌مان مستقل است از forms.ModelForm اگه فرمی که می‌خواهیم بسازیم وابسته به مدل خاصی باشد، باید از 
#'forms.ModelForm': Directly tied to a specific model. You specify which model to use in the Meta class, and it automatically generates fields based on that model.
#'forms.Form': Does not have any direct association with a model. You define all fields manually, and it can be used for various purposes (e.g., search forms, login forms).
#let's go ahead and create a new form for our search.
class ProductSearchForm(forms.Form):
    h = forms.CharField()  #we're not gonna build a form, we're gonna utilize Django and tell Django what type of form we want and we do that by basically set  up this variable 'q'('h') (query).Basically we're gonna say from 'forms' we just want to build a character field input. we just told Django that we want to make a new form and we want one input and that's just gonna be a character field. (ساختیم product_search و ویوای به نام views.py رفتیم توی فایل)
    cgry = forms.ModelChoiceField(queryset=Category.objects.exclude(name='default').order_by('name'))#next up we want to add the drop-down facility so not only do we want the user to be able to search for a word, we want to be able to let them select a category we want to search within. 'ModelChoiceField' is gonna create a drop-down choice field.

    #The __init__ method in a Django form is used to customize the form's initialization process. This defines the constructor for the form class. It allows you to pass additional arguments and keyword arguments when creating an instance of the form.
    def __init__(self, *args, **kwargs): #we're gonna return some arguments back
        super().__init__(*args, **kwargs) #This calls the parent class's (forms.Form) constructor, ensuring that any initialization defined in the parent class is also executed. This is essential for maintaining proper functionality.
        self.fields['cgry'].required = False #we're gonna select the field 'cgry' and put it as unrequired

        self.fields['cgry'].label = 'Category' #This sets a custom label for the cgry field that will be displayed in the form.
        self.fields['h'].label = 'Search For' #Similar to the previous line, this sets a custom label for the search input field h, changing its label to "Search For".

        self.fields['h'].widget.attrs.update(
            {'class': 'form-control menudd'})
        self.fields['h'].widget.attrs.update( #This line adds a data attribute called data-toggle, which is commonly used with Bootstrap to enable dropdown functionality when interacting with elements. It indicates that this input field can trigger a dropdown menu.
            {'data-toggle': 'dropdown'})
        #Field Definitions:
            # h: A character field for entering the search term.
            # cgry: A dropdown field for selecting a category, which excludes any category named "default".

templates/store/aa.html
<form class="d-flex my-2 my-lg-0" action="/search/" method="get">
    <!--ما را به صفحه سرچ میفرسد-->
    <input class="form-control mr-sm-2 search-input" name="h" type="search" placeholder="Search" aria-label="Search"
     required>
    <!--here 'h' is basically the name of the parameter that's gonna be utilized in the url to make a get request-->
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
   </form>
    {% if user.is_authenticated %}
    <form action="{% url 'account:logout' %}" method="post" style="display: inline;">
     {% csrf_token %}
     <button type="submit" class="btn btn-outline-success my-2 my-sm-0" style="margin-left: 20px;">
      <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-door-closed"
       viewBox="0 0 16 16">
       <path d="M3 2a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v13h1.5a.5.5 0 0 1 0 1h-13a.5.5 0 0 1 0-1H3V2zm1 13h8V2H4v13z" />
       <path d="M9 9a1 1 0 1 0 2 0 1 1 0 0 0-2 0z" />
      </svg>
      <span class="fs15 fw500">Logout</span>
     </button>
    </form>
    <!--we can't use an anchor (<a>) tag for the logout button. When you click this link, it sends a GET request to '/account/logout/', which is not allowed by the 'LogoutView'. The 'LogoutView' expects a POST request to log the user out.
                    To resolve this issue, you need to change the logout button to submit a POST request instead of using an anchor tag. You can do this by wrapping the button in a <form> element.
                    -->
    {% else %}
    <a type="button" role="button" href="{% url "account:login" %}" class="btn btn-outline-success my-2 my-sm-0"
     style="margin-left: 20px;">
     <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-door-closed"
      viewBox="0 0 16 16">
      <path d="M3 2a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v13h1.5a.5.5 0 0 1 0 1h-13a.5.5 0 0 1 0-1H3V2zm1 13h8V2H4v13z" />
      <path d="M9 9a1 1 0 1 0 2 0 1 1 0 0 0-2 0z" />
     </svg>
     <span class="fs15 fw500">Login</span>
    </a>
    {% endif %}

    <a type="button" role="button" href="{% url 'account:dashboard' %}" class="btn btn-outline-success my-2 my-sm-0"
     style="margin-left: 20px;">
     <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-person"
      viewBox="0 0 16 16">
      <path
       d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z" />
     </svg>
     Account
    </a>


    <a type="button" role="button" href="{% url 'basket:basket_summary' %}"
     class="btn btn-outline-success my-2 my-sm-0 " style="margin-left: 20px;">
     <!--We're asking Django to look for the 'app_name' that is equal to 'basket' and then we're asking it to look for the url (link) named 'basket_summary'. So it's just basically going to generate this url, based on this path, for me.-->

     {% with total_qty=basket|length %}
     <!--The 'basket' here is coming from the 'context_processor'. that 'length' is essentially gonna call the '__len__' method in basket.py-->
     <!--In Django templates, the 'length' filter is used to get the number of items in a collection, such as a list or a dictionary. When you apply the 'length' filter to an object, Django checks if that object has a '__len__()' method defined.-->
     <div id="basket-qty" class="d-inline-flex circle">
      <!--This class puts all the div's subsequent elements in a row-->
      {% if total_qty > 0 %}
      {{ total_qty }}
      {% else %}
      0
      {% endif %}
     </div>
     {% endwith %}

     <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-basket-fill"
      viewBox="0 0 16 16">
      <path
       d="M5.071 1.243a.5.5 0 0 1 .858.514L3.383 6h9.234L10.07 1.757a.5.5 0 1 1 .858-.514L13.783 6H15.5a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-.5.5H15v5a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V9H.5a.5.5 0 0 1-.5-.5v-2A.5.5 0 0 1 .5 6h1.717zM3.5 10.5a.5.5 0 1 0-1 0v3a.5.5 0 0 0 1 0zm2.5 0a.5.5 0 1 0-1 0v3a.5.5 0 0 0 1 0zm2.5 0a.5.5 0 1 0-1 0v3a.5.5 0 0 0 1 0zm2.5 0a.5.5 0 1 0-1 0v3a.5.5 0 0 0 1 0zm2.5 0a.5.5 0 1 0-1 0v3a.5.5 0 0 0 1 0z" />
     </svg>
     Basket
    </a>

   </div>
  </div>
 </nav>

templates/store/home.html
{% extends "./base.html" %}
{% load static %}
{% block title %}HomePage{% endblock %}
{% block content %}


<div class="album py-5 bg-light">
 <div class="container">

  <div class="pb-3 h4">All Products</div>
  <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-4">

   {% for product in products %}
   <!--The 'products' here is related to 'product_all' view in views.py-->

   <div class="col">
    <div class="card md-4 box-shadow">
     <a href="{{ product.get_absolute_url }}">
      <img class="img-fluid" alt="Responsive image" src="{{ product.image.url }}">
     </a>
     <div class="card-body">
      <p class="card-text">
       <a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}">
        <h2 style="font-size:18px; font-weight:bold;">{{ product.title }}</h2>
       </a>
      </p>
      <div class="fw-bold text-success">£{{product.price}}</div>
     </div>
    </div>
   </div>

   {% endfor %}

  </div>
 </div>
</div>
{% endblock %}

templates/store/search.html
{%extends "./base.html" %}

{%block title%}
Search Page
{%endblock%}
{% block content %}
<div class="container pt-5">
    {% if h %} <!--If there is data in 'q' (if someone actually has typed in something into the input) then display all that information and all that posts that are returned from the search, else show the form-->
    <h1>Products containing "{{ h }}"
            {% if cgry %}
            In category "{{ cgry }}":
            {% endif %}
    </h1>
    <p>
        {% with results.count as total_results %}
        Found {{ total_results }} result{{ total_results|pluralize }}
        {% endwith %}
    </p>

    <div class="album py-2 bg-light">
        <div class="container">
            <div class="row">
    {% for product in results %}
    <!-- <h5><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h5> -->
    <div class="col-md-4 mb-4">
        <a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}">
            <div class="col">
                <div class="card md-4 box-shadow">
                 <a href="{{ product.get_absolute_url }}">
                  <img class="img-fluid" alt="Responsive image" src="{{ product.image.url }}">
                 </a>
                 <div class="card-body">
                  <p class="card-text">
                   <a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}">
                    <h2 style="font-size:18px; font-weight:bold;">{{ product.title }}</h2>
                   </a>
                  </p>
                  <div class="fw-bold text-success">£{{product.price}}</div>
                 </div>
                </div>
               </div>
        </a>
    </div>
    {% empty %} <!--if there isn't anything returned, lt's just gonna say there are no results for your query.-->
    <p>There are no results for your query.</p>
    {% endfor %}
    <p><a href="{% url "store:product_search" %}" class="btn btn-primary my-1" role="button" aria-disabled="true">New Search</a></p>
    {% else %}
    <h1 class="my-4">Search for products</h1>
    <form class="dropdown" method="get"> <!--we're gonna be utilizing the method 'get' to send the data or query data that someone types into the input field to search for an item by 'get'-->
        <!-- {{ form.as_p }} this gonna create a loop and loop out all the items (fields) that we request (in this case according to our form 'h' and 'cgry' fields). what we can also do is we can select individual components to output. for example in this case we have two inputs ('h' and 'cgry'), and instead of {{ form.as_p}} if we write {{ form.h }} or {{ form.cgry }} only 'h' or 'cgry' field would be shown  -->
        <!--That basically renders the form as a series of <p> tags with each p containing one field.-->
        <!--The expression {{ form.as_p }} in your Django template is a convenient way to render a Django form as HTML, specifically wrapping each form field in <p> (paragraph) tags.-->
        <!--نیاز داریم برای این دراپ داون unordered list هدف این بود که وقتی کاربر در قسمت سرچ دارد تایپ می‌کند لیستی از پیشنهادات را به صورت دراپ داون مشاهده کند، بنابراین به یک -->
        {% csrf_token %} <!--we need to include this inside our form else you keep getting an error -->
        {{ form.h }}
        <ul class="dropdown-menu col-12 pl-2" role="menu" aria-labelledby="menu" id="list">
            <!--Now we need to make the actual input field as the trigger to actually trigger this drop-down.to do that we go back into 'forms.py' and what we're gonna need to do is add a class inside of our 'h' item so that Bootstrap can pick this up as the actual item that we're gonna click on to make that drop-down appear. we need to add a new attribute called 'data-toggle' with a value equal to 'dropdown'-->
        </ul>
        {{ form.cgry }}
        <input class="btn btn-primary my-1 mx-1" type="submit" value="search"> <!--so now the basic components of the form is being constructed we now gonna head over to the views and just set up the logic so that we can capture that data and then return the results to the template.in views we create a container for the results (a list)-->
    </form>
    {% endif %}
</div>
</div>
</div>
</div>
<script>
    //  an AJAX implementation that sends a POST request when a user types into the search input field (with the ID '#id_h'):
    $(document).on('keyup', '#id_h', function (e) {  //The code listens for the 'keyup' event on an input field with the ID '#id_h'. This means that every time a user releases a key while typing in this input field, the function will execute.
        e.preventDefault(); 
        var minlength = 3; //The code checks if the length of the input value is at least 3 characters before sending an AJAX request. This helps reduce unnecessary requests to the server.
        //برای بهینه کردن تعداد کوئری‌هایی که به دیتابیس می‌زنیم. اینجا مثلا می‌گیم اجازه بده تا حداقل 3 تا حرف تایپ بشه و بعد پیشنهادات را (که حاصل کوئری زدن به دیتابیسه) نشون بده
        var results =[];
            //This is a jQuery AJAX call that sends an asynchronous HTTP request to a server. 
        if ($('#id_h').val().length >= minlength) {   //before we actually run the AJAX we can check if the minimum length of the value user has typed in is 3 or not. 
            //AJAX POST Request: 
            //The AJAX call is made using jQuery's $.ajax() method:
            $.ajax({ // we create an AJAX POST request, simply by describing the type:'POST', so l'm gonna be utilizing 'POST', l'm gonna send the data across to the server utilizing 'POST',url:'' l need to define where l'm gonna send the data, data: {}, and then the actual data l want to send across.That's all l need to do to make a request (AJAX request). lf the item is successful and this data been returned we're then gonna return that data, that's gonna be returned in this variable called 'json' (you can change this to whatever you want, that's where the data is gonna reside that gets returned from the server) and then  
                type: 'POST', //The 'type' parameter is set to 'POST', indicating that this is a POST request.
                url:'{% url "store:product_search" %}', //we're gonna send this data to our view (our 'product_search' view, according to 'urls.py' file we can access that view via 'post_search'.) 
                data:{
                    ss: $('#id_h').val(),  //That is what l'm gonna send to the server. 'ss'is the current value of the input field ($('#id_h').val()), which represents the search string.
                //$('#id_h').val(): This is a jQuery expression that retrieves the current value of the input field with the ID id_h.
                //The $('#id_h') part selects the input element based on its ID.
                //The '.val()' method gets the value of that input element, which could be any text entered by the user.
                    csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(), //in order to get this working we're gonna need to include a csrf cross site request forgery value (Django is expecting a csrf token, so if we don't include this,this simply wouldn't work.)
                    action: 'post' //This is basically a hook that we're gonna use once we start writing the view. we can query this action, so if this action doesn't exist then we won't run the query so we can utilize it in that manner. 
                    },
                success: function (json) {  //This function will be called if the AJAX request is successful. The response from the server would typically be passed as a parameter (json) to this function, allowing you to handle it appropriately.
                    // document.getElementById("list").innerHTML = json.search_string //we're using innerHTML to replace items within our unordered list by id="list" with whatever we have returned from the database or view as a string (remember that the data is returned and is stored in this 'json'variable)  //when someone types in to search for items returns data from the database (search suggestions) that's basically gonna overwrite all these items in the unordered list with id = 'list'.
                    // console.log(json.search_string)//را در صفحه وب می‌زنیم کارایی دارد inspect برای دیباگ کردن وقتی  //just to log the json and then search_string. just remember although we're storing the data in 'json' here, when we return the data we're actually storing it in the (reference of) 'search_string' so the data is inside of this 'search_string' reference here which is a property of the 'json' object returned by the server (view).
                //بعد از دیدن نتیجه دو خط بالایی، کامنتشان کردیم و خطهای پایینی را نوشتم
                //we want generate a loop, we want to loop through the data that's returned and just output the title.
                    $.each(JSON.parse(json.search_string), function (i, item) {
                //let's remember that we've returned the data as a string so we're gonna need to json.parse that so that we can format it so we can read it as json. so we go ahead and select what we want to format (in this case 'json.search_string'). we are using 'each()' it is essentially a 'for each' loop using Jquery.
                //so we create this loop, l'm returning the 'i' and 'item' we just essentially make a reference point and the actual data will be in 'item' so we will be able to access the data from 'item'.
                //so we're gonna loop through each 'item' that is returned and we're gonna take the 'item' and we're gonna utilize 'push' because for each item we're gonna update the variable called 'results'.
                        //results.push(item.fields.title)
                        results.push('<li class="mx-2 my-2 pl-2"><a style="text-decoration: none;" href="/products/' + item.fields.slug +'/">' + item.fields.title +'</a></li>')
                    })
                    if (!$(".show")[0]) {//if there is 'not' a class (element) called 'show', then we're gonna set a trigger on the 'menudd' and that's gonna actually trigger the drop-down to work// l'm using jquery to search my document for a class called 'show', if the dropdown doesn't exist there won't be a class called 'show' 
                        $('.menudd').trigger('click')
                    }

                    document.getElementById("list").innerHTML = (!results.length) ? "No results match your query" : results.join(''); //'(!results.length)':This checks whether the 'results' array is empty. 'results.length' returns the number of elements in the 'results' array. The '!' operator negates this value, so if 'results.length' is '0' (indicating that the array is empty), '!results.length' evaluates to true.
                         //Ternary Operator:The expression uses a ternary operator, which is a shorthand way to write an if-else statement.
                        //The syntax (in javascript) is:
                        //condition ? valueIfTrue : valueIfFalse;
                
                    //document.getElementById("list").innerHTML = results;  //all the data in 'results' array would have been loop through and placed inside of this array.
                    //document.getElementById("list").innerHTML = results.join(''); //برای خلاص شدن از شر اون ویرگول بین آیتم‌های لیست دراپ داون
                
                },
                error: function (xhr, errmsg, err) {//function (xhr, errmsg, err) { ... }: This function will be called if there is an error with the AJAX request. It provides parameters that can help diagnose what went wrong.
                }
            });
    }})
</script>
{% endblock %}
<!--
success: function (json) { ... }:
 This defines a callback function that is executed when the AJAX request is successful. The 'json' parameter represents the data returned from the server, which is expected to be in JSON format.
document.getElementById("list").innerHTML = json.search_string;:
 This line updates the inner HTML of an HTML element with the ID 'list'.
 It sets the content of this element to the value of 'search_string', which is a property of the 'json' object returned by the server.
 If 'json.search_string' contains a string or HTML content, it will replace whatever is currently inside the element with that value.
console.log(json.search_string);:
 This line logs the value of 'json.search_string' to the console.
 This is useful for debugging purposes, allowing you to see what value was returned from the server and ensure that it is being processed correctly.
-->