account/urls.py
from django.contrib.auth import views as auth_views #the pre-built views for the authentication processes (like Login\Logout processes). we're gonna hook into that and override some of the settings. we can do this in the 'views.py' but we're just gonna lay all this out in the urls.py.
from django.urls import path
from . import views
from django.views.generic import TemplateView
from .forms import (PwdResetConfirmForm, PwdResetForm, UserLoginForm)


app_name = 'account' #it should be the same as 'namespace' in 'path('account/', include('account.urls', namespace='account')),' that we wrote in core/urls.py. It makes it much easier for us to call our urls in our templates for example.

urlpatterns = [
    path('register/', views.account_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>/', views.account_activate, name='activate'), #according to the url in 'account_activation_email.html' we have got the 'uid' (user id) and the 'token'. so there are two things here that we're passing in to our url and we're trying to capture those. 
    # User dashboard
    path('dashboard/', views.dashboard, name='dashboard'), #This new path called 'dashboard' is gonna connect to views.dashboard
    path('login/', auth_views.LoginView.as_view(template_name='account/registration/login.html',
                                                form_class=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/account/login/'), name='logout'), #when a user logs out, the next page, where the user is gonna be taken to, is the login page.
    path('profile/edit/', views.edit_details, name='edit_details'),
    path('profile/delete_user/', views.delete_user, name='delete_user'),
    path('profile/delete_confirm/', TemplateView.as_view(template_name="account/dashboard/delete_confirm.html"), name='delete_confirmation'),
    # Reset password
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="account/password_reset/password_reset_form.html",
                                                                 success_url='password_reset_email_confirm', #to tell the user that "if you can check your email you'll then be able to reset your password".
                                                                 email_template_name='account/password_reset/password_reset_email.html', 
                                                                 form_class=PwdResetForm), name='pwdreset'),

    #'password_reset_confirm/<uidb64>/<token>': This is the format similar to what we’ve done previously when we activated the account so we need to take in these parameters (uidb64) and (token) so that we can verify the user when they click on the link that has been sent to their email.
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset/password_reset_confirm.html',
                                                                                                success_url='/account/password_reset_complete/', 
                                                                                                form_class=PwdResetConfirmForm,), name="password_reset_confirm"),
    #by paying attention to the last two pathes, you will realize that in the first path, we start our 'success_url' with no '/' but in the second path we do. 
    # having a '/' at the start means that we want to continue the url that we're currently using. but when we use '/' it is referring to the root directory. 
    # so in the first path we redirect to 'http://127.0.0.1:8000/account/password_reset/password_reset_email_confirm/' as the success url, but in the second one we redirect to 'http://127.0.0.1:8000/account/password_reset_complete/'as the success url.
    
    path('password_reset/password_reset_email_confirm/',
         TemplateView.as_view(template_name="account/password_reset/reset_status.html"), name='password_reset_done'), #for showing 'Password Reset Success Check your email for instructions'.
    path('password_reset_complete/',
         TemplateView.as_view(template_name="account/password_reset/reset_status.html"), name='password_reset_complete'), #for showing 'Password Reset Completed! login'
    path("addresses/", views.view_address, name="addresses"), #It is like a HomePage for the addresses.
    path("add_address/", views.add_address, name="add_address"), #for this we need a form.
    path("addresses/edit/<slug:id>/", views.edit_address, name="edit_address"), #when we edit we're going to pass in the id of the actuall address we want to edit into the view, so then we can run the query against that id and collect the right address to edit.
    path("addresses/delete/<slug:id>/", views.delete_address, name="delete_address"), #We’re going to do the same type of thing here for deleting the address, so we’re gonna need to be able to identify what we want to delete so the view is going to bring up an address.
    path("addresses/set_default/<slug:id>/", views.set_default, name="set_default"),
    path("user_orders/", views.user_orders, name="user_orders"),
    # Wish List
    path("wishlist", views.wishlist, name="wishlist"),
    path("wishlist/add_to_wishlist/<int:id>", views.add_to_wishlist, name="user_wishlist"), 
    #We need to capture the ID of the product the user clicked on to add it to their wishlist. When the user clicks the button, we'll pass the product ID from the frontend to the 'add_to_wishlist' view.
]

basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'


# 'basket/' is the prefix (root) for the rest of the urls here:
urlpatterns = [
    path('', views.basket_summary, name='basket_summary'), #the path is the root and then I want to connect this url to a view called 'basket_summary' where we're gonna show all the items in the basket. we can easily access this url through its name 'basket_summary'.
    path('add/', views.basket_add, name='basket_add'), #where we're gonna send the AJAX request created within 'singleproduct.html' off to.
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
# from azbankgateways.urls import az_bank_gateways_urls
# from checkout.bank import go_to_gateway_view, callback_gateway_view

#we use 'namespace' to refer to a view for avoiding hardcoding.
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')), #It's better to separate our URLs into the application level.'' is the root directory and the HomePage. and namespace will allow us later on in the program to kind of access our URLs in a more convenient way.
    path('basket/', include('basket.urls', namespace='basket')), #we can't have two pathes starting from the root.
    path('account/', include('account.urls', namespace='account')),
    path('checkout/', include("checkout.urls", namespace="checkout")), #It creates a connection to our checkout/urls.py file.
    path('orders/', include('orders.urls', namespace='orders')),
    # # bankgetways urls
    # path('bankgateways/', az_bank_gateways_urls()),
    # path('go-to-gateway/', go_to_gateway_view, name='go-to-gateway'),
    # path('callback-gateway/', callback_gateway_view),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#We can either write it like the line below or above.
# if settings.DEBUG:  #while we're working in the development environment (opposite of production environment) we have got "DEBUG = True" and that provides us an additional information when we make mistakes in our project and we can kind of view them in the browser, of course we don't want that to happen in our production environment so we turn that off.
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = 'store' #this name should be equal to the namespace in 'core/urls.py'.

#here we need to connect our URLs to the views.
urlpatterns = [
    path('', views.product_all, name='product_all'), #this is the root directory. this view is gonna be all the products (I could just call this HomePage).
    path('products/<slug:slug>/', views.product_detail, name='product_detail'), #we want to connect the URL 'products/<slug:slug>/' to the individual product page so we've connected this URL to the 'product_detail' view.
    path('categories/<slug:category_slug>/', views.category_list, name='category_list'),
    path('search/', views.product_search, name='product_search'),
]

store/forms.py
from django import forms #by this we brought in 'forms' module from Django framework.
from store.models import Product, Category #by this we can grap the data from 'Product' table.

# ارث‌بری می‌کنیمforms.Form ارث‌بری کنیم و در کلاس متا هم اسم آن مدلی که قرار است فرم را براساسش بسازیم، می‌نویسیم. در مقابل اما اگر فرم‌مان مستقل است از forms.ModelForm اگه فرمی که می‌خواهیم بسازیم وابسته به مدل خاصی باشد، باید از 
#'forms.ModelForm': Directly tied to a specific model. You specify which model to use in the Meta class, and it automatically generates fields based on that model.
#'forms.Form': Does not have any direct association with a model. You define all fields manually, and it can be used for various purposes (e.g., search forms, login forms).
#let's go ahead and create a new form for our search.
class ProductSearchForm(forms.Form):
    h = forms.CharField()  #we're not gonna build a form, we're gonna utilize Django and tell Django what type of form we want and we do that by basically set  up this variable 'q'('h') (query).Basically we're gonna say from 'forms' we just want to build a character field input. we just told Django that we want to make a new form and we want one input and that's just gonna be a character field. (ساختیم product_search و ویوای به نام views.py رفتیم توی فایل)
    cgry = forms.ModelChoiceField(queryset=Category.objects.exclude(name='default').order_by('name'))#next up we want to add the drop-down facility so not only do we want the user to be able to search for a word, we want to be able to let them select a category we want to search within. 'ModelChoiceField' is gonna create a drop-down choice field.

    #The __init__ method in a Django form is used to customize the form's initialization process. This defines the constructor for the form class. It allows you to pass additional arguments and keyword arguments when creating an instance of the form.
    def __init__(self, *args, **kwargs): #we're gonna return some arguments back
        super().__init__(*args, **kwargs) #This calls the parent class's (forms.Form) constructor, ensuring that any initialization defined in the parent class is also executed. This is essential for maintaining proper functionality.
        self.fields['cgry'].required = False #we're gonna select the field 'cgry' and put it as unrequired

        self.fields['cgry'].label = 'Category' #This sets a custom label for the cgry field that will be displayed in the form.
        self.fields['h'].label = 'Search For' #Similar to the previous line, this sets a custom label for the search input field h, changing its label to "Search For".

        self.fields['h'].widget.attrs.update(
            {'class': 'form-control menudd'})
        self.fields['h'].widget.attrs.update( #This line adds a data attribute called data-toggle, which is commonly used with Bootstrap to enable dropdown functionality when interacting with elements. It indicates that this input field can trigger a dropdown menu.
            {'data-toggle': 'dropdown'})
        #Field Definitions:
            # h: A character field for entering the search term.
            # cgry: A dropdown field for selecting a category, which excludes any category named "default".

templates/store/products/category.html
{% extends "../base.html" %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}
<main>
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="container" style="max-width: 1000px">
        <div class="col-12">
          <h1 class="h2">{{ category.name|title }}</h1>
        </div>
        <div class="col-12 d-flex justify-content-between">
          <div><b>Popular</b> products purchased</div>
        </div>
        <hr />
      </div>
      <div class="pb-3 h5">{{ category.name | title }}</div>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

        {% for product in products %} <!--The 'products' here is related to 'all_products' view in views.py-->

        <div class="col">
          <div class="card md-4 box-shadow">
            <a href="{{ product.get_absolute_url }}">
                <img class="img-fluid" alt="Responsive image" src="{{ product.image.url }}">
            </a>
            <div class="card-body">
              <p class="card-text">
                <a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}"><h2 style="font-size:18px; font-weight:bold;">{{ product.title }}</h2></a>
              </p>
              <div class="fw-bold text-success">£{{product.price}}</div>
            </div>
          </div>
        </div>

        {% endfor %}

      </div>
    </div>
  </div>
</main>
{% endblock %}

templates/store/products/singleproduct.html
{% extends "store/base.html" %}
{% load static %}
{% block title %}
{{ product.title }}
{% endblock %}

{% block content %}
<div class="container my-5">
    <main>
        {% if messages %}
        <div class="alert alert-success" alert-{{ message.tags }}" role="alert">
        {% for message in messages  %}
        {{message|safe}} - <a href="{% url "account:wishlist" %}" class="alert-link">Your Wishlist</a>.
        {% endfor %}
        </div>
        {% endif %}
        <div class="row g-4">
            <div class="col-md-5 col-lg-5 order-md-first">
                <img class="img-fluid rounded shadow" alt="{{ product.title }}" src="{{ product.image.url }}">
            </div>
            <div class="col-md-7 col-lg-7">
                <h1 class="mb-3 h4 text-primary"><h2><b>{{ product.title }}</b></h2></h1>
                <p class="lead text-muted"><span class="fw-bold">{{ product.author }}</span> (Author)</p>
                
                <div id="description-container">
                    <div class="product-description">
                        <p style="color: black;" id="short-description">
                            <span class="a-text-bold">{{ product.description|safe|slice:":355" }}...</span>
                        </p>
                        <!-- Full description is hidden initially -->
                        <p style="color: black;" class="d-none" id="full-description">{{ product.description|safe }}</p>
                    </div>
                </div>
                
                <button id="toggle-description" class="btn btn-link p-0 text-primary" style="text-decoration: none;">Read More</button>

                <div class="card border-light mt-3">
                    <div class="card-body">
                        <div class="d-flex justify-content-between border-bottom pb-2 mb-3">
                            <div><h4><b>Price:</b></h4></div>
                            <div><span class="h4 fw-bold text-success">£{{ product.price }}</span></div>
                        </div>
                        <div class="d-flex justify-content-between align-items-center">
                            <div>
                                <label for="select">Qty</label>
                                <select id="select" class="form-select d-inline-block w-auto" >
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                </select>
                            </div>
                            <!-- <button type="button" id="add-button" value="{{product.id}}" class="btn btn-primary btn-sm">Add to Basket</button> -->

                                <div class="d-grid gap-2 ">
                                    <button type="button" id="add-button" value="{{product.id}}" class="btn btn-success fw500">Add to basket</button>
                                    {% with request.user.user_wishlist.all as wishlist %}
                                    <a href="{% url 'account:user_wishlist' product.id %}" 
                                       class="btn btn-secondary fw500 wishlist-button" 
                                       role="button" 
                                       id="wishlist-button-{{ product.id }}" 
                                       data-in-wishlist="{% if product in wishlist %}true{% else %}false{% endif %}">
                                       {% if product in wishlist %}
                                           Remove from Wish List
                                       {% else %}
                                           Add to Wish List
                                       {% endif %}
                                    </a>
                                    {% endwith %}
                                    
                                 
                                 <!--we also pass over the the id of the product, because we have <int:id> in the url 'path("wishlist/add_to_wishlist/<int:id>", views.add_to_wishlist, name="user_wishlist")'-->
                                </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
</div>

<script>
$(document).ready(function() {
    $("#toggle-description").click(function() {
        // Toggle visibility of short and full descriptions
        $("#short-description").toggleClass("d-none"); // Hide short description
        $("#full-description").toggleClass("d-none"); // Show full description
        
        // Change button text based on current state
        $(this).text($(this).text() === "Read More" ? "Read Less" : "Read More");
    });
});
</script>
<!--jQuery AJAX request:-->
<!--uses jQuery to handle a button click event and send an AJAX request to a Django backend.-->
<script>
    //This line uses jQuery's $(document).on() method to attach a click event listener to the element with the ID add-button. This is a jQuery way of handling events.
    $(document).on('click', '#add-button', function (e) {  
        e.preventDefault();
        //let's just test to make sure we can select:
        //jQuery Selector:
            // $('#select option:selected'): This uses jQuery to select the currently selected <option> within the <select> element with the ID 'select'.
            // #select: This targets the <select> element by its ID.
            // option:selected: This selects the <option> that is currently selected by the user.
            // Getting Text Content:
            // .text(): This jQuery method retrieves the text content of the selected <option>. For example, if a user selects "2", this method will return "2".
            // Logging to Console:
            // console.log(...): This function outputs whatever is passed to it into the browser's console. It’s useful for debugging and checking values during development.
        //console.log($('#select option:selected').text()) or the line below
        console.log($('#select option:selected').val())
        //2)AJAX Request:
        //sending some data:
        $.ajax({ //making an AJAX request to send some data to the server and then return data.
            type: 'POST',
            //we're gonna send the AJAX request off to a url which is connected to a view and in this way, we can go to the backend and capture this information:
            url: '{% url "basket:basket_add" %}', //where we're gonna send this data, that's gonna be connected to a url, that url is gonna be connected to a view (behind the scenes). The 'url' parameter uses the {% url "basket:basket_add" %} tag to dynamically generate the correct endpoint for adding items to a basket. This ensures that when the AJAX request is made, it points to the correct view handling that action.
            data: {
                productid: $('#add-button').val(), //grabbing the value: we're just telling JavaScript to have a look for the value of an element for which id="add-button".
                productqty: $('#select option:selected').text(),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            //receiving a response (which is asynchronous) :
            //term 'asynchronous' refers to the ability of the web application to perform tasks without blocking the user interface or requiring the entire webpage to reload.
            success: function (json) { // We're going to reference that returned data as 'json' because it is in JSON format.
               console.log(json) //it's gonna show the total gty into the console.
               //3) DOM Manipulation: (The term DOM stands for Document Object Model. It is a programming interface that browsers use to represent and interact with HTML and XML documents.)
               document.getElementById("basket-qty").innerHTML = json.qty 
               //Accessing the Element: This JavaScript line accesses the <div> element with the ID 'basket-qty' (which is in base.html).
               //Updating Inner HTML: It sets the inner HTML of that element to the value of 'json.qty'.
               //When the Django template renders, it calculates total_qty based on the length of basket and displays that value in the <div>.
               //Later, when you run the JavaScript code, it updates the content of that same <div> to whatever value is contained in 'json.qty'.
               //which means assigns the total_qty in {{ total_qty }} the value of 'json.qty'.
               //although we're not working on 'base.html', that will get rendered with this page (singleproduct.html) and because this will be loaded in the DOM, so we can access the id of an element within 'base.html' and change its inner HTML value.
                    //The Document Object Model (DOM) is a crucial concept in web development that allows programmers to interact with HTML and XML documents.
                    // What is the DOM?
                    // Definition:
                    // The DOM is an application programming interface (API) that represents the structure of a document as a tree of objects. It allows programs (like JavaScript) to access and manipulate the content, structure, and style of web pages dynamically.
                    // Tree Structure:
                    // The DOM represents a document as a hierarchical tree structure, where each element in the HTML or XML document is a node in the tree. For example, an HTML document might have a root node (the <html> element), with child nodes for <head>, <body>, and so on.
                    // Manipulation:
                    // Using the DOM, developers can:
                    // Add: new elements to the document.
                    // Modify: existing elements (e.g., changing text or attributes).
                    // Delete: elements from the document.
                    // This manipulation can happen in response to user actions (like clicks or key presses), allowing for dynamic web applications.
            },
            error: function (xhr, errmsg, err) {}
        });
    })
</script>
<script>
    //To add an effect when the button is clicked, you can use jQuery to create visual feedback for the user:
    $(document).on('click', '#add-button', function (e) { //'#add-button' refers to the class, '.add-button' refers to the id.
        e.preventDefault();
    
        // Change button color
        $(this).css('background-color', 'green');
    
        // Optional: Reset color after a short delay
        setTimeout(() => {
            $(this).css('background-color', '');
        }, 500); // Change back after 500 milliseconds
    
        // Your AJAX code here...
    });
    </script>

    
{% endblock %}
<!--
Definition of Asynchronous in AJAX
Non-blocking Operations: Asynchronous operations allow a program to initiate a task and then continue executing other code without waiting for that task to complete. 
In AJAX, this means that when a request is made to the server, the user can still interact with the webpage while waiting for the server's response.

User Experience: Because AJAX requests are handled asynchronously, users can continue to browse or interact with other elements of the webpage without interruption. 
This leads to a smoother and more responsive user experience compared to synchronous requests, where the entire page would freeze until the server responds.

Background Data Exchange: In AJAX, data can be sent and received in the background. For example, when a user submits a form or clicks a button, an AJAX call can fetch data from the server without requiring a full page reload. 
The results can then be used to update specific parts of the webpage dynamically.

Example: When you click a button that fetches new content (like comments or product details), an AJAX call is made asynchronously. 
While waiting for this data, you can still scroll through other content on the page or interact with different elements.
In summary, asynchronous in "AJAX asynchronous JavaScript" allows for efficient data handling and improved user interaction by enabling background processes that do not disrupt the user's experience on the webpage.
-->

<!--
Purpose of Using % url % Template Tag
Dynamic URL Generation: The % url % template tag allows you to generate URLs based on the view names ('namespace') defined in your Django 'urls.py' file. 
This is particularly useful because it avoids hardcoding URLs in your JavaScript code, which can lead to issues if the URL structure changes.

Maintainability: If you later change the URL pattern for the "basket:basket_add" view in your Django application, you won't need to update it in multiple places within your JavaScript code. 
Instead, you only need to update it in one location (the 'urls.py' file), and the % url % tag will automatically reference the new URL.

Avoiding Hardcoding: Hardcoding URLs can lead to errors, especially in larger applications where multiple developers might be working on different parts of the codebase. Using the % url % tag helps ensure that all parts of your application reference URLs consistently.
Contextual Awareness: The % url % tag takes into account any parameters required by the view, making it easier to construct URLs that may vary based on user input or other dynamic factors.
-->